version: '3'

services:
  db:
    image: postgres:12.1-alpine
    environment: 
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_dev
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    environment: 
      - DATABASE_URI=postgresql://db_username:db_password@db/db_dev
    depends_on: 
      - db
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - backend
  